language: go

go:
  - "1.12.x"

services:
  - docker

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file: build/main
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: make upload-master
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: make upload-tag
    skip_cleanup: true
    on:
      tags: true

